import * as React from "react";
import type { IProcedureCall } from "src/models";

interface IProps {
  calls?: readonly Readonly<IProcedureCall>[];
}

const ProcedureCallBadge: React.FC<IProps> = ({ calls }) => {
  if (calls === undefined || calls.length === 0) {
    return null;
  }

  const label = calls
    .map((call) => [call.name, ...call.arguments].join(" "))
    .join(" → ");

  return (
    <span
      className="procedureCallBadge"
      title={`Generated by procedure call: ${label}`}
    >
      <span aria-hidden="true">ƒ</span>
      <code>{label}</code>
    </span>
  );
};

export default ProcedureCallBadge;
